branches:
  only:
    - master

image:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Release

matrix:
  fast_finish: true
  allow_failures:
    - platform: x86
      configuration: Release

install:
  # Install Tcl/Tk
  - cmd: set IRONTCL_VERSION="8.6.7"
  - cmd: if %platform%==x86 set DOWNLOAD_PLATFORM=win32
  - cmd: if %platform%==x64 set DOWNLOAD_PLATFORM=amd64
  - cmd: if %platform%==x86 set CMAKE_GENERATOR="Visual Studio 15"
  - cmd: if %platform%==x64 set CMAKE_GENERATOR="Visual Studio 15 Win64"
  - cmd: appveyor DownloadFile https://www.irontcl.com/downloads/irontcl-%DOWNLOAD_PLATFORM%-%IRONTCL_VERSION%.zip
  - cmd: cmake -E tar xf irontcl-%DOWNLOAD_PLATFORM%-%IRONTCL_VERSION%.zip
  - cmd: set PATH=%cd%\IronTcl\bin;%PATH%
  # Generate solution...
  - cmd: cmake -E make_directory "build"
  - cmd: cd build && cmake -G %CMAKE_GENERATOR% -D CMAKE_INSTALL_PREFIX=runtime ..

build:
  project: C:\projects\tkdnd\build\tkdnd.sln      # path to Visual Studio solution or project

after_build:
  - cmd: msbuild INSTALL.vcxproj

artifacts:
  - path: '\build\runtime\**\*'
    type: zip
    name: tkdnd-%platform%
