branches:
  only:
    - master

image:
  - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Release

matrix:
  fast_finish: true
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release

for:
-
  matrix:
    only:
      - platform: x86
  environment:
  DOWNLOAD_PLATFORM: win32

for:
-
  matrix:
    only:
      - platform: x64
  environment:
  DOWNLOAD_PLATFORM: amd64

install:
  # Install Tcl/Tk
  - cmd: set IRONTCL_VERSION="8.6.7"
  - cmd: appveyor DownloadFile https://www.irontcl.com/downloads/irontcl-%DOWNLOAD_PLATFORM%-%IRONTCL_VERSION%.zip
  - cmd: cmake -E tar xf irontcl-%DOWNLOAD_PLATFORM%-%IRONTCL_VERSION%.zip
  - cmd: set PATH=%cd%\IronTcl\bin;%PATH%
  # Generate solution...
  - cmd: cmake .
