name: arm-crosscompile

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "arm64"

      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tcl tcl-dev tk tk-dev build-essential wget unzip tcllib tcllib-critcl libxcursor-dev gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build
        run: |
          cd cmake
          bash buildarm64.sh
          cd release-nmake-aarch64
          make install

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.5
        with:
          name: linux-arm
          path: cmake/release-nmake-aarch64/lib/tkdnd2.9.4
